name: Build, Test, and Deploy

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - "scripts/**"
      - "pyproject.toml"
      - "uv.lock"
      - "Dockerfile"
      - "docker-compose*.yaml"
      - "infra.py"
      - "openapi.json"
      - ".pre-commit-config.yaml"
      - ".github/workflows/**"
  workflow_dispatch:
    inputs:
      deploy:
        description: Deploy if tests successful
        required: true
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  check-version:
    name: Check Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for version tagging

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Check version
        # https://github.com/gnprice/toml-cli
        run: |-
          VERSION=$(uvx --from=toml-cli toml get --toml-path pyproject.toml project.version)
          git tag "v$VERSION"

  lint-format-and-static-code-checks:
    name: Lint, Format, and Static Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # we need to fetch all branches/history so we can grab openapi.json out of the main branch
          fetch-depth: 0
      # we need docker to run the oasdiff CLI pre-commit hook
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      # run the pre-commit hooks including the openapi hooks to check any breaking changes
      # in the openapi schema/contract. If contract has breaking changes, the build will fail.
      - name: Run oasdiff, Lint, Format, and other static code quality checks
        run: SKIP=no-commit-to-branch uvx --from pre-commit pre-commit run --all-files

  build-wheel:
    name: Build Wheel Dist & Upload as Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Build Wheel Dist
        run: uv build --wheel

      - name: Upload Wheel Dist
        uses: actions/upload-artifact@v4
        with:
          name: wheel-dist
          path: ./dist/*

  execute-tests:
    name: Execute Tests against Wheel
    needs:
      - build-wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Download Wheel Dist
        uses: actions/download-artifact@v4
        with:
          name: wheel-dist
          path: ./dist/

      - name: Install Wheel & Run Tests against Wheel
        run: |-
          uv venv
          source .venv/bin/activate
          uv pip install ./dist/*whl
          uv pip install --group test
          bash +x ./run run-tests

  deploy:
    name: Deploy to AWS
    needs:
      [
        execute-tests,
        build-wheel,
        lint-format-and-static-code-checks,
        check-version,
      ]
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    # IDEAL WAY to do this would be deploy to dev/staging on PR merge, then either
    # Deploy to prod on merge to main or have a manual approval step.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Node
        uses: actions/setup-node@v6

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        # ^^^needed for building and deploying Lambda Layer

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-west-2

      - name: CDK Synthesize
        run: bash +x ./run cdk-synth

      - name: CDK Deploy
        run: bash +x ./run cdk-deploy --require-approval never

  publish:
    name: Publish Version Tag
    needs: [deploy]
    runs-on: ubuntu-latest
    # if - this is a merge to main or push directly to the main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Download Wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel-dist
      # - name: Deploy
      #   if: ${{ github.event.inputs.deploy == 'true' }}
      #   run: |
      #     # ...
      - name: Push Version Tag
        # https://github.com/gnprice/toml-cli
        run: |-
          VERSION=$(uvx --from=toml-cli toml get --toml-path pyproject.toml project.version)
          git tag "v$VERSION"
          git push origin --tags
